spring:
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    url: jdbc:h2:mem:hidongmin37
    username: sa
    password:
    driver-class-name: org.h2.Driver
mybatis:
  configuration:
    map-underscore-to-camel-case: true
  type-aliases-package: hidongmin37.com.cocomunity.api.domain